#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

echo "##################################"
echo "# Copy configuration files"
echo "##################################"

echo "Copying .bashrc"
cp ../config/bashrc ~/.bashrc

echo "Copying .vimrc"
cp ../config/vimrc ~/.vimrc
