#!/bin/bash

# This script creates the right directory structure I need

printf "\n\n"
echo "###############################"
echo "# OTHER CONFIGURATION"
echo "###############################"
echo "Creating Projects and Scripts folder in Home directory"
test -d ~/projects || mkdir ~/projects
test -d ~/scripts || mkdir ~/scripts
