#!/bin/bash

# This script installs all the packages I use for development on a Debian box at FamilySearch

#Function that installs a package, given its name
function install-package {
  apt-get -y install $1
  if [ $? -ne 0 ]; then
    echo "Error installing $1"
    exit 1
  fi
}

#Function that pretty-prints an install header message
function print-header {
  printf "\n\n"
  echo "###############################"
  echo "# Installing $1"
  echo "###############################"
}

#Install Apache2
print-header apache2
install-package apache2

#Install Java7 (OpenJDK)
print-header openjdk-7-jdk
install-package openjdk-7-jdk

#Install Maven
print-header maven
install-package maven

#Install Git
print-header git
install-package git

#Install Ruby
print-header ruby
install-package ruby1.9.1

#Install Vim
print-header vim
install-package vim

#Install other packages
print-header "other-development-tools-packages"
install-package curl
install-package libreadline6-dev
install-pacakge zlib1g-dev
install-package libssl-dev
install-package libyaml-dev
install-package libsqlite3-dev
install-package sqlite3
install-package libxml2-dev
install-package libxslt1-dev
install-package autoconf
install-package libgdbm-dev
install-package libncurses5-dev
install-package automake
install-package "make"
install-package libtool
install-package bison
install-package libffi-dev
install-package libexpat1-dev
install-package build-essential
install-package terminator

printf "\n\n"
