#!/bin/bash

# This script runs the OS updates for all the packages on my system
#Run updates for Ubuntu
echo "###############################"
echo "# RUNNING UPDATES"
echo "###############################"
apt-get update
apt-get -y upgrade

if [ $? -ne 0 ]; then
  echo "Error running updates"
  exit 1
fi

printf "\n\n"
