#!/usr/bin/env python

"""update-repos: Iterates through the subdirectories in the current directory and does a git pull on any git repos"""

import os
from subprocess import call

orig_dir = os.getcwd()
for current_item in os.listdir(orig_dir):
    if os.path.isdir(current_item):
        os.chdir(current_item)
        if os.path.exists(".git"):
            print("##################################")
            print("Status for {}".format(current_item))
            print("##################################")
            call(["git", "status"])
            print("\n")
        os.chdir("..")