#!/bin/bash

# Get relevant files on my machine
bootstrap/setup-dirs-and-scripts

# Set up Vim with preferred settings
bootstrap/setup-vim

# Lay down environment configuration files
bootstrap/apply-environments-config

